install.packages("readr")
library(readr)
monster_jobs <- read.csv("monster_jobs.csv")
monster_jobs_clean <- read.csv("monster_jobs_clean.csv")
n_cols <- ncol(monster_jobs)
n_rows <- nrow(monster_jobs)
names <- colnames(monster_jobs)
n_cols_clean <- ncol(monster_jobs_clean)
n_rows_clean <- nrow(monster_jobs_clean)
names_clean <- colnames(monster_jobs_clean)
monster_jobs_head <- head(monster_jobs)
monster_jobs_tail <- tail(monster_jobs)
install.packages("ggplot2")
library(ggplot2)
salary_min_viz <- qplot(x=job_id, y = salary_min,data = monster_jobs_clean)
qplot(x=job_id, y = salary_min,color = job_type,data = monster_jobs_clean)
install.packages("modelr")
